name: nutrivita_demo_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dropdown_button2: ^2.3.9
  path_provider: ^2.1.5
  flutter_inset_box_shadow: ^1.0.8
  google_nav_bar: ^5.0.7
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/en.json
    - assets/pl.json
    - assets/category_group.json
    - assets/surveyFoods.json
    - assets/USDA.png
    - assets/USDA3.png
    - assets/cut_survey_foods.json
    - assets/cut_survey_foods_pl.json
    - assets/v2/category_group_v2.json
    - assets/v2/sorted_SF_by_category_desc_nolimit/carbohydrates.json
    - assets/v2/sorted_SF_by_category_desc_nolimit/energy.json
    - assets/v2/sorted_SF_by_category_desc_nolimit/fatty_acids.json
    - assets/v2/sorted_SF_by_category_desc_nolimit/minerals.json
    - assets/v2/sorted_SF_by_category_desc_nolimit/other.json
    - assets/v2/sorted_SF_by_category_desc_nolimit/proteins.json
    - assets/v2/sorted_SF_by_category_desc_nolimit/sugars.json
    - assets/v2/sorted_SF_by_category_desc_nolimit/vitamins.json
    - assets/v2/sorted_SF_by_category_desc_nolimit/fdc_ranking_map.json
    - assets/v2/sorted_SF_by_category_desc_top30/carbohydrates.json
    - assets/v2/sorted_SF_by_category_desc_top30/energy.json
    - assets/v2/sorted_SF_by_category_desc_top30/fatty_acids.json
    - assets/v2/sorted_SF_by_category_desc_top30/minerals.json
    - assets/v2/sorted_SF_by_category_desc_top30/other.json
    - assets/v2/sorted_SF_by_category_desc_top30/proteins.json
    - assets/v2/sorted_SF_by_category_desc_top30/sugars.json
    - assets/v2/sorted_SF_by_category_desc_top30/vitamins.json
    
