name: nutrivita_demo_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dropdown_button2: ^2.3.9
  path_provider: ^2.1.5
  flutter_inset_box_shadow: ^1.0.8
  google_nav_bar: ^5.0.7
  sqflite: ^2.4.2
  path: ^1.9.1
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  collection: ^1.19.1
  dartz: ^0.10.1
  slang_flutter: ^4.9.0
  slang: ^4.9.2
  flutter_localizations:
    sdk: flutter
  get_it: ^9.0.5
  msgpack_dart: ^1.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.26.2

  

flutter:
  uses-material-design: true
  assets:
    - assets/USDA3.png
    - assets/demo.jpg
    - assets/demo.mp4
    - assets/demo.gif
    - assets/nutrivita.jpg
    - assets/v2/sorted_SF_by_category_desc_nolimit/carbohydrates.json
    - assets/v2/sorted_SF_by_category_desc_nolimit/energy.json
    - assets/v2/sorted_SF_by_category_desc_nolimit/fatty_acids.json
    - assets/v2/sorted_SF_by_category_desc_nolimit/minerals.json
    - assets/v2/sorted_SF_by_category_desc_nolimit/other.json
    - assets/v2/sorted_SF_by_category_desc_nolimit/proteins.json
    - assets/v2/sorted_SF_by_category_desc_nolimit/sugars.json
    - assets/v2/sorted_SF_by_category_desc_nolimit/vitamins.json


    
